name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build, Lint, and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftFormat and SwiftLint
        run: brew install swiftformat swiftlint

      - name: SwiftFormat check
        run: swiftformat . --lint --quiet



      - name: Build and Test
        run: |
          xcodebuild test \
            -project TicTacToe.xcodeproj \
            -scheme TicTacToe \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -quiet