name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build, Lint, and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        run: xcodebuild test -project TicTacToe.xcodeproj -scheme TicTacToe -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' -quiet