name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build, Lint, and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftFormat and SwiftLint
        run: brew install swiftformat swiftlint

      - name: SwiftFormat check
        run: swiftformat . --lint --quiet

      # Use Xcode version compatible with current project file format
      # Use Xcode version compatible with project file format (objectVersion 77)
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app



      - name: Build and Test
        run: |
          xcodebuild test \
            -project TicTacToe.xcodeproj \
            -scheme TicTacToe \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -quiet